# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b3847bc91697216904eff0691304e7fca040fab118dd73265889be5ca3066dab83ca581a49caa14dc50485c439349ca13de89b62c97f450729bc7aa5085a40cb

test:
  secret_key_base: fc8278c3dafa3e7ba16600cc17f12c10ca898a52d63738d75928fa9827fd5ae106eedc5c2de430e741c719e029fe614f11875a9cc801189b1c9f33a0151a1418

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
